using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace API.Models.User;

/// <summary>
/// Represents a player in the system.
/// </summary>
/// <remarks>
/// A player object includes an identifier, a name, a score, and a reference to a related factory.
/// Each player has a one-to-one relationship with a factory in the database.
/// </remarks>
public class Player {
#region Variables
    /// <summary>
    /// Gets or sets the unique identifier for the player.
    /// </summary>
    /// <remarks>
    /// This property is used as the primary key in the database to uniquely identify a player.
    /// It is of type <c>int</c> and is automatically generated by the database when a new
    /// player is created.
    /// </remarks>
    [Key]
    [Column(TypeName = "int")]
    public int Id { get; set; }

    /// <summary>
    /// Gets or sets the name of the player.
    /// </summary>
    /// <remarks>
    /// This property represents the player's name, which is of type <c>string</c>.
    /// It is stored in the database as a <c>varchar(100)</c>. The name is used to identify
    /// a player in various operations such as creation, retrieval, and deletion.
    /// </remarks>
    [Column(TypeName = "varchar(100)")]
    public string Name { get; set; } = String.Empty;

    /// <summary>
    /// Gets or sets the score of the player.
    /// </summary>
    /// <remarks>
    /// This property represents the player's current score in the system.
    /// It is an integer value that can be updated during gameplay.
    /// </remarks>
    [Column(TypeName = "int")]
    public int Score { get; set; } = 0;

    /// <summary>
    /// Gets or sets the amount of money associated with the player.
    /// </summary>
    /// <remarks>
    /// This property represents the player's current monetary value in the game.
    /// It is stored as an integer in the database and can be updated to reflect gains or deductions.
    /// </remarks>
    [Column(TypeName = "int")]
    public int Money { get; set; } = 50;

    // Navigation Property: Ein Player hat genau eine Factory
    public Factory.Factory? Factory { get; set; }

    /// <summary>
    /// Gets or sets a value indicating whether the player is in two-player mode.
    /// </summary>
    public bool TwoPlayerMode { get; set; } = false;
#endregion

#region Services
    // No Services
#endregion

#region Constructors
    // No Constructors
#endregion

#region Methods
    // No Methods
#endregion

#region Event Handlers
    // No Event Handlers
#endregion
}
